@startuml
!theme bluegray
autonumber


actor Поставщик as user
participant Фоторедактор as editor
database tags as db
queue Queue as queue
participant Статика as basket
participant Потребители as consumers

user -> editor: ui
editor -> db: rest api
db ->> queue
basket ->> queue
consumers -> basket

@enduml